# Generated by Django 4.2 on 2026-07-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_employee_maintenance_assetassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='123456', max_length=100),
            preserve_default=False,
        ),
    ]
