# Generated by Django 4.2 on 2026-07-14 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_asset_asset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.employee'),
            preserve_default=False,
        ),
    ]
