# Generated by Django 4.2 on 2026-07-21 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_maintenance_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recycling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycle_date', models.DateField()),
                ('method', models.CharField(choices=[('Recycle', 'Recycle'), ('Reuse', 'Reuse'), ('Scrap', 'Scrap')], max_length=20)),
                ('reason', models.TextField()),
                ('recycled_by', models.CharField(max_length=100)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.asset')),
            ],
        ),
    ]
